# Generated by Django 3.2.8 on 2021-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_through_atc',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
