# Generated by Django 3.2.8 on 2021-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_subservice_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_service',
        ),
        migrations.AddField(
            model_name='service',
            name='sub_service',
            field=models.ManyToManyField(to='core.SubService'),
        ),
    ]
