# Generated by Django 3.2.8 on 2021-10-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211022_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sub_service',
        ),
        migrations.AddField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
